services:
  - type: web
    name: form-acudientes
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: COSMO_RLT_db
          property: connectionString

databases:
  - name: COSMO_RLT_db
    databaseName: form_acudientes
    user: form_acudientes_user
    plan: free